# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /blog/:categories/:year/:month/:day/:title

port: 4445

exclude: ["Rakefile", "Gemfile", "README.md", "style/less/"]
pygments: true

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Burnish
tagline: Quietly Making Software
author :
  name : Philip Blackwell
  email : hello@burnish.cc
  github : burnish
  twitter : blackp
  feedburner : feedname

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://www.burnish.cc

env: prod